config/routes.rb
Rails.application.routes.draw do
  get 'chats/new'
  get 'chats/create'
  post 'chats/start'
  get 'chats/video'
  get 'chats/index'
  mount ActionCable.server => '/cable'
  get 'messages/new'
  post 'messages/create'
  get 'messages/index'
  get 'rooms/new'
  post 'rooms/create'
  get 'rooms/index'
  root 'pages#index'

  get 'pages/path'
  resources :rooms do
  get 'stoptyping', action: :stoptyping, on: :collection
  get 'typingstatus', action: :typingstatus, on: :collection
    member do
      get :show
    end
  end
  post 'rooms/start'


  
  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :photo
  after_create_commit { MessageBroadcastJob.perform_now(self) }
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    validates :name, presence: true

    def self.create_private_room(users, room_name)
        single_room = Room.create(name: room_name)
        single_room
      end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages

  def self.online
    ids = ActionCable.server.pubsub.redis_connection_for_subscriptions.smembers "online"
    where(id: ids)
  end

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    chats_index_path
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def new
  end


  def index
    ActionCable.server.pubsub.redis_connection_for_subscriptions.sadd "online", current_user.id
    respond_to do |format|
      format.turbo_stream
      format.html { render 'pages/index'}
    end
  end
  
  def start
    ActionCable.server.broadcast "session_channel", session_params
  end
  
  def video
    @localuser = params[:user_id]
    @user = User.find(params[:user_id])
    @current_user = current_user
    @room = Room.new
    @message = Message.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @messages = @single_room.messages
    render 'video'
  end


private
  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end

  def session_params
    params.require(:chat).permit(:type, :from, :to, :sdp, :candidate, :room, :receiver)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(user_id: current_user.id, room_id: params[:room_id], content: params[:content],photo: params[:photo] )
    @message.save if params[:content].present? || params[:photo].present?
    # @room = Room.includes(:messages,{messages: :user}).find(params[:id])
    # @messages = @room.messages.with_attached_photo.includes(:user,{photo_attachment: :blob})
    # @rooms = Room.all
    # respond_to do |format|
    #   format.html 
    #   format.js
    # end
    # render "rooms/show"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @rooms = Room.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


  def create
    @room = Room.create(name: params[:name])
    redirect_back(fallback_location: root_path)
  end

  def video
    head :no_content
    ActionCable.server.broadcast "session_channel", session_params
  end

  def show
    @room = Room.includes(:messages,{messages: :user}).find(params[:id])
    @messages = @room.messages.with_attached_photo.includes(:user,{photo_attachment: :blob})
    @rooms = Room.all
  end
  
  def stoptyping
    ActionCable.server.broadcast "typing_channel",{user_id: "#{current_user.id}",id: "#{params[:room]}",message: ' is Typing', body: "#{current_user.name}"}
  end
  
  def typingstatus
    ActionCable.server.broadcast "styping_channel", {user_id: "#{current_user.id}",id: "#{params[:room]}",message: "", body: "#{current_user.name}"}
  end

  def start
    # ActionCable.server.broadcast "session_channel", session_params
    ActionCable.server.broadcast "session_channel", {type: "#{params[:type]}",from: "#{params[:from]}",to: "#{params[:to]}",sdp: "#{params[:sdp]}",candidate: "#{params[:candidate]}",room: "#{params[:room]}"}
  end

  private
    def session_params
      params.require(:room).permit(:type, :from, :to, :sdp, :candidate, :room)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def create
        head :no_content
        ActionCable.server.broadcast "session_channel", session_params
    end
  
    private
    def session_params
        params.require(:video).permit(:type, :from, :to, :sdp, :candidate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/index.js.erb
console.log("---------------------")
my_function(
console.log("---------------------")
  location.reload();
);

app/views/chats/new.html.erb
<h1>Chats#new</h1>
<p>Find me in app/views/chats/new.html.erb</p>

app/views/chats/show.html.erb
<h1>Chats#show</h1>
<p>Find me in app/views/chats/show.html.erb</p>

app/views/chats/video.html.erb
<%= User.find(@localuser).name %>
<% if User.online.include? User.find(@localuser) %>
  <div id="<%= @localuser %>" style="color:green; "><%=  "online" %></div>
  <button id="join-button">Start Call</button>
<% else %>
  <div id="<%= @localuser %>" style="color:red; "><%=  "offline" %></div>
  <button style="display:none;" id="join-button">Start Call</button>
<% end %>

<div  style="color:green;display: none; "><%=  "online" %></div>

<br>user id:-<span id="currentuser"><%= @localuser %></span>
caller id:-<span id="calleruser"><%= current_user.id %></span><br>

<button style="display: none" id="leave-button">Leave Call</button>


<video style="width:300px;" id="localvideo" autoplay></video>
<span id="remote-video-container"></span>

<button style="display: none" onclick="vidOff()" id="offvideo">Off Video</button>
<button style="display: none" onclick="vidOn()" id="onvideo">On Video</button><br>


<div id="allmessages">
  <%= render partial: "messages/messages" %>
</div>
<div class="form-group msg-form">
  <%= form_with(url: messages_create_url, class: "d-flex",data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
    <%= f.hidden_field :room_id, value: "#{@single_room.id}" %>
    <%= f.text_field :content, id: 'chat', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.file_field :photo %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>


<script>
  let localstream;
  
  function vidOff() {
    localstream.getTracks()[0].enabled = false;
    localstream.getTracks()[1].enabled = false;
  }

  function vidOn() {
    localstream.getTracks()[0].enabled = true;
    localstream.getTracks()[1].enabled = true;
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<style>
  <%= ".cont-#{current_user&.id}" %> {
  display: flex;
  justify-content: flex-end
  }
</style>

<%= link_to "Home", root_path , class: "btn btn-danger" %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <div style="margin: 0 10px;text-align:left;"class="btn btn-info"><h5><%= message.user.name if sameuser %></h5>
      <% if message.content.present? %>
        <div id="sameuser-<%= message.id %>" >
          <%= message.content %>
        </div>
      <% end %>
      <% if message.photo.attached? %>
        <div id="message-photo">
          <%=  image_tag message.photo,style: "width:100px;height:100px;" %>
        </div>
      <% end %>
    </div><br>
  </div>
</div>

app/views/messages/_messages.html.erb
<% @messages.each_with_index do |message, index| %>
  <div id="messages">
    <% if message.room.messages[index - 1].user.id == message.user.id && index != 0 %>
      <%= render partial: 'messages/message',locals: { message: message ,sameuser: false} %>
    <% else %>
      <%= render partial: 'messages/message',locals: { message: message, sameuser: true } %>
    <% end %>
  </div>
<% end %>

<div id="typing-<%=@room.id%>">
  <span style="opacity:0;"><%=current_user.id%></span>
</div>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/messages/ncreate.js.erb
$("#allmessages").html("<%= escape_javascript(render('messages/message')) %>");

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/pages/_user.html.erb
<%= tag.li user.email, data: { id: user.id } %>

app/views/pages/_users.html.erb
<% User.all.each do |user| %>
  <div class="btn btn-danger" ><%= user.name %></div>
<% end %>

app/views/pages/index.html.erb
<% if user_signed_in? %>

  <div><strong>hey</strong> <%= current_user&.name %></div>

  <% User.all.each do |user| %>
    <% unless user == current_user %>
      <span style="margin:10px;"><%= link_to user.name , chats_video_path(user_id: user.id), method: :get  ,class: "btn btn-primary" %></span>
    <% end %>
  <% end %>

    
  <h1>Users online</h1>

  <ul id="online-users">
    <%= render partial: "pages/user", collection: User.online, as: :user %>
  </ul>

  <%#= link_to "video room", chats_index_path, class: "btn btn-primary" %>

  <%#= form_with(url: rooms_create_url, remote: true, class: "d-flex",id: "new_message" ) do |f| %>
    <%#= f.text_field :name, class: "form-control", autocomplete: 'off',id: "message_content" %>
    <%#= f.submit data: { disable_with: false } %>
  <%# end %><br>

  <div id="rooms">
    <%#= render @rooms %>
  </div>

  <% end %>
<script>
</script>

app/views/rooms/_room.html.erb
<%=  link_to room.name, room , class: "btn btn-primary" %><span style="margin:5px;"></span>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/new.html.erb
<h1>Rooms#new</h1>
<p>Find me in app/views/rooms/new.html.erb</p>

app/views/rooms/show.html.erb
<% if user_signed_in? %>
  <div><strong>hey</strong> <%= current_user&.name %></div>
  <%= form_with(url: rooms_create_url, remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :name, class: "form-control",id: "chat_text", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false } %>
  <% end %>
  <br><div id="rooms">
    <%= render @rooms %>
  </div>

<% end %>

<br><span style="margin: 0 10px">Room-</span><%= @room.name %><br><br>

<div id="allmessages">
  <%= render partial: "messages/messages" %>
</div>

<div class="form-group msg-form">
  <%= form_with(url: messages_create_url, class: "d-flex",data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
    <%= f.hidden_field :room_id, value: "#{@room.id}" %>
    <%= f.text_field :content, id: 'chat', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.file_field :photo %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>


<hr>Room id:-<span id="currentuser"><%=  @room.id %></span>
User id:-<span id="calleruser"><%= current_user.id %></span><hr>


<button id="join-button">Join Call</button>
<button id="leave-button">Leave Call</button>

<button onclick="vidOff()" id="onvideo">Off Video</button>
<button onclick="vidOn()" id="offvideo">On Video</button><br>

<video  style="width:200px; height:200px;" id="localvideo" autoplay></video>
<span id="remote-video-container"></span>


<script>
  let localstream;

  navigator.webkitGetUserMedia(options, function(stream) { 
    localvideo.srcObject = stream;
    localstream = stream;
    localvideo.play();
    }, function(e) { 
        }); 
  function vidOff() {
    console.log("video off")
    //clearInterval(theDrawLoop);
    //ExtensionData.vidStatus = 'off';
    localvideo.pause();
    localvideo.src = "";
    localstream.getTracks()[0].stop();
    localstream.getTracks()[1].stop();
  }


  function vidOn() {
  if (navigator.mediaDevices.getUserMedia !== null) {
    var options = { 
    video:true, 
    audio:true 
    };  
    navigator.webkitGetUserMedia(options, function(stream) { 
    localvideo.srcObject = stream;
    localstream = stream;
    localvideo.play();
    }, function(e) { 
        }); 
    }
  }

  $(document).ready(function(){
    var tmo = null;
    $("#chat").on("input", function(){
      $.ajax({
        type: 'GET',
        url: '/rooms/stoptyping',
        data: {"room":"<%= @room.id %>"},
      });
      if (tmo) {
        clearTimeout(tmo);
      }
      tmo = setTimeout(function () {
        $.ajax({
          type: 'GET',
          url: '/rooms/typingstatus',
          data: {"room":"<%= @room.id %>"},
      });
      }, 700);
    });
  });
</script>